In [1]:
import numpy as np

In [2]:
a = [[1,2,3],[4,5,6]]
b = [[7,8,9],[0,1,3]]

a = np.array(a)
b = np.array(b)

c = np.hstack((a, b))
d = np.vstack((a, b))
print(c)
print(c.shape)
print()
print(d)
print(d.shape)

[[1 2 3 7 8 9]
 [4 5 6 0 1 3]]
(2, 6)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 3]]
(4, 3)


In [3]:
e = [1,2,3]
f = [4,5,6]
e = np.array(e)
f = np.array(f)

In [4]:
g = np.hstack((e,f))
h = np.vstack((e,f))

print(g)
print(g.shape)
print()
print(h)
print(h.shape)

[1 2 3 4 5 6]
(6,)

[[1 2 3]
 [4 5 6]]
(2, 3)
