In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print("Shape of a:", a.shape)
print(type(a))

[1 2 3 4 5]
Shape of a: (5,)
<class 'numpy.ndarray'>


In [7]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print("Shape of b:", b.shape)
print(type(b))

# Shapes (5,) and (5, 1) are different
# (5, ) => Linear array, elements accessed as a[i]
# (5, 1) => 2D array of 5 rows and 1 column, elements accessed as b[i][0]

[[1]
 [2]
 [3]
 [4]
 [5]]
Shape of b: (5, 1)
<class 'numpy.ndarray'>


In [9]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print("Shape of c:", c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
Shape of c: (2, 3)
5


In [32]:
# Array of zeroes, ones, constants, identity matrix

a = np.zeros((3, 3))
print(a)
print()

b = np.ones((2, 3))
print(b)
print(type(b[1][2])) # => Each element is of float type in zeros/ones
print()

c = np.full((3, 2), 5)
print(c)
print()

d = np.eye(3)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.float64'>

[[5 5]
 [5 5]
 [5 5]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
# Random matrix (useful in neural networks)
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[0.86648286 0.88129731 0.54899013]
 [0.4449494  0.01803557 0.96990736]]


In [46]:
# To access all elements of second column => [rows, cols]
print(randomMatrix[ : , 1])

# To access all elements of third column
print(randomMatrix[ : , 2])

# To access second and third elements of second row
print(randomMatrix[1, 1:])

[0.88129731 0.01803557]
[0.54899013 0.96990736]
[0.01803557 0.96990736]


In [47]:
# Updating second and third elements of second row
randomMatrix[1, 1:] = 1        # ==> Slicing operation
print(randomMatrix)

[[0.86648286 0.88129731 0.54899013]
 [0.4449494  1.         1.        ]]


In [53]:
z = np.zeros((3,3))
print(z)
print()

z[1, :] = 5  # Second row, all columns as 5
z[:, -1] = 7 # All rows, last column as 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [58]:
x = np.zeros((3,3))
x[1, :] = 5
print(x)
print(x.dtype)

y = np.zeros((3,3), dtype = np.int64)
y[1, :] = 5
print(y)
print(y.dtype)

[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [5 5 5]
 [0 0 0]]
int64


### Mathematical Operations
- Add: x+y or np.add(x, y)
- Subtract
- Multiply
- Divide
- Square Root
- Dot Product
- Sum (axis-wise)

In [67]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x+y)
print(np.add(x, y))
print()

print(x-y)
print(np.subtract(x, y))
print()

# Element-wise multiplication (not matrix multiplication or dot product)
print(x*y)
print(np.multiply(x, y))
print()

print(x/y)
print(np.divide(x, y))
print()

print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [69]:
# Matrix Multiplication (Dot Product)

print(x)
print(y)

print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [71]:
# Dot Product of Vectors => Returns a Scalar
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print(a.dot(b))

30


In [74]:
print(a)
print(sum(a))

[1 2 3 4]
10


In [87]:
print(x)

print(sum(x))                 # => Normal sum gives column-wise sum
print(np.sum(x))              # => Sum of all matrix elements
print()

print(np.sum(x, axis = 0))    # => Column-wise sum when axis = 0
print(np.sum(x, axis = 1))    # => Row-wise sum when axis = 1

[[1 2]
 [3 4]]
[4 6]
10

[4 6]
[3 7]


### Stacking of Arrays

In [92]:
a = b = np.array([1, 2, 3, 4])
print(a, b)
b = b**2
print(a, b)

[1 2 3 4] [1 2 3 4]
[1 2 3 4] [ 1  4  9 16]


In [97]:
print(np.stack((a, b), axis = 0))  # => Stack arrays column wise, so each array becomes a row
print(np.stack((a, b), axis = 1))  # => Stack arrays row wise, so each array becomes a column

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


### Reshaping a Numpy Array

In [111]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print("Shape:", a.shape)
print()

print(a.reshape(4, 2))
print()

print(a.reshape(8,1))
print()

print(a.reshape(8,))
print()

[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

[1 2 3 4 5 6 7 8]



In [120]:
# When either no. of rows/columns are unknown: use -1
print(a)
print()

print(a.reshape(4, -1)) # => 4 rows, unknown cols, therefore, 2 cols, as total num of elements = 8
print()

print(a.reshape(-1, 4)) # => unknown rows, 4 cols, therefore, 2 rows
print()

print(a.reshape(-1, 8)) # => unknown rows, 8 cols, therefore, 1 row
print()

print(a.reshape(8, -1)) # => 8 rows, unknown cols, therefore, 1 col

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4 5 6 7 8]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### Statistical Operations
- Min, max
- Mean
- Average
- Median
- Standard Deviation
- Variance

In [125]:
a = np.array([[1, 2, 3, 4], [6, 7, 0, 9]])
print(a)

print(np.min(a))            # => Overall minimum
print(np.min(a, axis = 0))  # => Col wise minimum
print(np.min(a, axis = 1))  # => Row wise minimum

[[1 2 3 4]
 [6 7 0 9]]
0
[1 2 0 4]
[1 0]


In [130]:
b = np.array([1, 2, 3, 4, 5])
print(sum(b)/len(b))

print(np.mean(b))
print()

print(np.mean(a))            # Overall mean
print(np.mean(a, axis = 0))  # Col wise mean
print(np.mean(a, axis = 1))  # Row wise mean

3.0
3.0

4.0
[3.5 4.5 1.5 6.5]
[2.5 5.5]


In [133]:
c = np.array([1, 3, 5, 2, 7])
d = np.array([1, 3, 5, 2, 7, 6])
print(np.median(c))
print(np.median(d))

3.0
4.0


In [139]:
# Mean vs Average ==> Average is weighted mean where weights are specified as a separate array

print(np.mean(c))                  # Unweighted

print(np.average(c))               # Default is unweighted if weights array not specified (weights = None as default)
w = [1, 2, 3, 4, 5]
w2 = [1, 1, 1, 1, 1]
print(np.average(c, weights=w))
print(np.average(c, weights=w2))

3.6
3.6
4.333333333333333
3.6


In [142]:
# Standard Deviation and Variance

# SD = sqrt [(1/N) * Sum (Xi - U)^2]
u = np.mean(c)
mySD = np.sqrt(np.mean(abs(c - u)**2))
print(mySD)
print(np.std(c))

# Variance
print(mySD**2)
print(np.var(c))

2.1540659228538015
2.1540659228538015
4.64
4.64


### Numpy Random Module

In [165]:
# Arange(): To generate a range from 'start' to 'stop' with increment as 'step'

a = np.arange(10)
print(a)

b = np.arange(10) + 5
print(b)

c = np.arange(3, 10, 2)
d = np.arange(4, 10, 2)
e = np.arange(10, 1, -1)
print(c)
print(d)
print(e)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[3 5 7 9]
[4 6 8]
[10  9  8  7  6  5  4  3  2]


In [175]:
np.random.shuffle(a)   # Changes the array itself
print(a)

[5 0 8 9 4 2 3 1 7 6]


In [200]:
# Random values from 0 to 1 (uniform distribution)
x = np.random.rand(3, 2)
print(x)
print()

# Random values from 0 to 1 (standard normal distribution)
y = np.random.randn(2, 3)
print(y)
print()

# Random int values from 'low' to 'high' (both inclusive)
print(np.random.randint(3, 10, 6))

[[0.41424477 0.63078536]
 [0.89224808 0.4218613 ]
 [0.89314689 0.22051986]]

[[ 1.26002588  0.71193179  0.76206702]
 [ 0.80425504 -1.53100459  0.61050203]]

[9 4 3 9 7 3]


In [214]:
# Randomly pick one element from a given list
e = np.random.choice([1, 6, 2, 8, 24, 7, 4])
print(e)

24


In [248]:
# Seed
a = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
np.random.seed(1)      # To store state of a random number, so same sequence is generated next time

# 1st shuffle will ALWAYS give [8 3 2 7 1 5 4 6] whenever we initialise array 'a' with 1 to 8 and shuffle once
# 2nd shuffle will ALWAYS give [2 7 1 6 3 4 8 5] whenever we initialise array 'a' with 1 to 8 and shuffle twice
# 3rd shuffle will ALWAYS give [6 2 5 4 3 1 7 8]
# Thus, random state is stored
# Sequence to be generated follows same pattern each time as seed value is 1

In [251]:
np.random.shuffle(a)
print(a)

[6 2 5 4 3 1 7 8]
